export const CELEBRATION_DISPLAY_MS = 1200;
export const CELEBRATION_EXIT_MS = 300;
export const CELEBRATION_SEQUENCE_MS = CELEBRATION_DISPLAY_MS + CELEBRATION_EXIT_MS;
export const WIN_PRESENTATION_DWELL_MS = 1000;
